// @ts-check
// "Generated by" detection: figure out which tool/agent produced a document by
// reading signals inside the markdown itself. The filesystem never records the
// creating application (owner is only the OS user), so the document body is the
// one place a generator can leave its mark. Pure + synchronous so it works on
// every surface (web included) and is easy to unit-test.
//
// Confidence order, highest first:
//   1. YAML front-matter keys (generator/creator/author/tool/…) — explicit.
//   2. An HTML comment marker (`<!-- specdown:creator=… -->` or a generic
//      `<!-- Generated by … -->`) — explicit, survives rendering.
//   3. A small set of specific generation signatures (e.g. a "Generated with
//      Claude Code" footer). Deliberately narrow: a bare mention of a name in
//      prose must NOT be mistaken for authorship.

// Front-matter keys we treat as naming the generator, in preference order.
const CREATOR_FRONT_MATTER_KEYS = [
  'specdown-creator',
  'specdown_creator',
  'generator',
  'generated_by',
  'generated-by',
  'creator',
  'created_by',
  'created-by',
  'tool',
  'made_by',
  'made-by',
  'author',
];

// Narrow, footer-style signatures → normalized tool name. Each regex must be
// specific enough that it can't fire on a document that merely discusses the
// tool by name.
const CREATOR_SIGNATURES = [
  { re: /Generated with \[?Claude Code\]?/i, name: 'Claude Code' },
  { re: /Co-Authored-By:\s*Claude\b/i, name: 'Claude' },
  { re: /\bgenerated by (?:chatgpt|gpt-[\d.]+|openai)\b/i, name: 'ChatGPT' },
  { re: /\b(?:made|generated|created) (?:with|by) cursor\b/i, name: 'Cursor' },
  { re: /\bgithub copilot\b/i, name: 'GitHub Copilot' },
  { re: /\bgenerated by (?:google )?gemini\b/i, name: 'Gemini' },
];

// Keep the surfaced value tidy: strip matched wrapping quotes and cap length so
// a runaway front-matter value can't blow out the sheet layout.
function tidyCreatorValue(/** @type {string} */ raw) {
  let value = String(raw).trim();
  const quote = value.match(/^(['"])([\s\S]*)\1$/);
  if (quote) value = quote[2].trim();
  if (value.length > 80) value = value.slice(0, 79).trimEnd() + '…';
  return value;
}

/**
 * Parse the leading YAML front-matter block into a flat key→value map. Only the
 * simple `key: value` scalar lines agents actually emit are read (no nested
 * structures) — enough to find a generator field without pulling in a YAML lib.
 * Returns null when there is no front-matter block.
 * @param {string} markdown
 * @returns {Record<string, string> | null}
 */
function extractCreatorFrontMatter(markdown) {
  // Tolerate a leading BOM but require the fence at the very start otherwise.
  const text = markdown.charCodeAt(0) === 0xfeff ? markdown.slice(1) : markdown;
  const match = text.match(/^---[ \t]*\r?\n([\s\S]*?)\r?\n---[ \t]*(?:\r?\n|$)/);
  if (!match) return null;

  /** @type {Record<string, string>} */
  const map = {};
  for (const line of match[1].split(/\r?\n/)) {
    // key: value — key is a bare word, value is the rest of the line.
    const kv = line.match(/^([A-Za-z][\w-]*)\s*:\s*(.*)$/);
    if (!kv) continue;
    const key = kv[1].toLowerCase();
    const value = tidyCreatorValue(kv[2]);
    if (value && !(key in map)) map[key] = value;
  }
  return map;
}

/**
 * Detect the generating tool/agent for a document from its content. Returns the
 * normalized name plus where it was found, or null when nothing is detected.
 * @param {string | null | undefined} markdown
 * @returns {{ creator: string, source: 'frontmatter' | 'comment' | 'signature', field?: string } | null}
 */
export function detectCreator(markdown) {
  if (typeof markdown !== 'string' || !markdown) return null;

  // 1. Front-matter fields.
  const frontMatter = extractCreatorFrontMatter(markdown);
  if (frontMatter) {
    for (const key of CREATOR_FRONT_MATTER_KEYS) {
      if (frontMatter[key]) {
        return { creator: frontMatter[key], source: 'frontmatter', field: key };
      }
    }
  }

  // 2. Explicit SpecDown marker, then a generic "Generated/Created/Made by/with"
  //    comment. Restricted to comment bodies so prose can't trip it.
  const specdownComment = markdown.match(
    /<!--\s*specdown\s*:\s*(?:creator|generator|created[-\s]?by)\s*[:=]\s*([^>]+?)\s*-->/i
  );
  if (specdownComment) {
    return { creator: tidyCreatorValue(specdownComment[1]), source: 'comment' };
  }
  const genericComment = markdown.match(
    /<!--\s*(?:generated|created|made)\s+(?:by|with)\s+([^>]+?)\s*-->/i
  );
  if (genericComment) {
    return { creator: tidyCreatorValue(genericComment[1]), source: 'comment' };
  }

  // 3. Known generation signatures (narrow by construction).
  for (const { re, name } of CREATOR_SIGNATURES) {
    if (re.test(markdown)) {
      return { creator: name, source: 'signature' };
    }
  }

  return null;
}
