/**
 * Unit tests for detectCreator (features/creator-detect.js) — inferring the
 * tool/agent that generated a document from signals inside the markdown, since
 * the filesystem never records the creating application.
 */

const { loadHTML, loadApp } = require('../helpers/loadApp');
require('../mocks/marked');
require('../mocks/mermaid');
require('../mocks/panzoom');
require('../mocks/highlightjs');

describe('detectCreator', () => {
  beforeEach(() => {
    loadHTML(document);
    loadApp(document);
  });

  it('returns null for empty or non-string input', () => {
    expect(detectCreator('')).toBeNull();
    expect(detectCreator(undefined)).toBeNull();
    expect(detectCreator(null)).toBeNull();
    expect(detectCreator('# Just a heading\n\nNo signals here.')).toBeNull();
  });

  describe('front-matter', () => {
    it('reads a generator field', () => {
      const md = '---\ntitle: Notes\ngenerator: Cursor\n---\n\n# Notes';
      expect(detectCreator(md)).toEqual({
        creator: 'Cursor',
        source: 'frontmatter',
        field: 'generator',
      });
    });

    it('reads author as a fallback and strips quotes', () => {
      const md = '---\nauthor: "Claude"\n---\nbody';
      const result = detectCreator(md);
      expect(result.creator).toBe('Claude');
      expect(result.source).toBe('frontmatter');
      expect(result.field).toBe('author');
    });

    it('prefers a more explicit key over author', () => {
      const md = '---\nauthor: Jane\ncreated_by: ChatGPT\n---\nbody';
      const result = detectCreator(md);
      expect(result.creator).toBe('ChatGPT');
      expect(result.field).toBe('created_by');
    });

    it('caps an overlong value', () => {
      const long = 'x'.repeat(200);
      const result = detectCreator(`---\ngenerator: ${long}\n---\n`);
      expect(result.creator.length).toBeLessThanOrEqual(80);
      expect(result.creator.endsWith('…')).toBe(true);
    });

    it('ignores a --- that is not at the very start', () => {
      const md = '# Title\n\n---\ngenerator: Cursor\n---\n';
      expect(detectCreator(md)).toBeNull();
    });
  });

  describe('comment markers', () => {
    it('reads an explicit specdown creator marker', () => {
      const md = '# Doc\n\n<!-- specdown:creator=Claude Code -->\n';
      expect(detectCreator(md)).toEqual({ creator: 'Claude Code', source: 'comment' });
    });

    it('reads a generic "Generated by" comment', () => {
      const md = 'body\n<!-- Generated by SomeAgent v2 -->';
      const result = detectCreator(md);
      expect(result.creator).toBe('SomeAgent v2');
      expect(result.source).toBe('comment');
    });
  });

  describe('signatures', () => {
    it('detects a Claude Code footer', () => {
      const md = 'text\n\nGenerated with [Claude Code](https://claude.ai/code)';
      expect(detectCreator(md)).toEqual({ creator: 'Claude Code', source: 'signature' });
    });

    it('detects a Co-Authored-By: Claude trailer', () => {
      const md = 'notes\n\nCo-Authored-By: Claude <noreply@anthropic.com>';
      expect(detectCreator(md)).toEqual({ creator: 'Claude', source: 'signature' });
    });

    it('detects "made with Cursor"', () => {
      expect(detectCreator('Made with Cursor').creator).toBe('Cursor');
    });

    it('does NOT fire on a bare mention of a tool in prose', () => {
      const md = '# Comparing agents\n\nCursor and Claude are both editors people discuss.';
      expect(detectCreator(md)).toBeNull();
    });

    it('front-matter wins over a signature elsewhere in the doc', () => {
      const md = '---\ngenerator: Cursor\n---\n\nGenerated with [Claude Code](x)';
      const result = detectCreator(md);
      expect(result.creator).toBe('Cursor');
      expect(result.source).toBe('frontmatter');
    });
  });
});
